---
version: '3'
services:
  freqtrade:
    image: freqtrade_custom
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    # links:
    #   - "binance_proxy"
    # depends_on:
    #   - "binance_proxy"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./freqtrade_strategies:/freqtrade/freqtrade_strategies"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    # ports:
    #   - "127.0.0.1:8081:8081"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade1.log
      --config /freqtrade/user_data/config1.json
      --config /freqtrade/user_data/config-exchange1.json
      --config /freqtrade/user_data/config-exchange-general.json
    #  --config /freqtrade/user_data/config-exchange-general-binance-proxy-docker.json
    #  --config /freqtrade/user_data/config-exchange-general-binance-proxy-futures.json
    #  --config /freqtrade/user_data/config-exchange-general-docker-kucoin.json
      --config /freqtrade/user_data/config-exchange-blacklist.json
      --config /freqtrade/user_data/config-telegram1.json
      --config /freqtrade/user_data/config-telegram-general.json
    #  --config /freqtrade/user_data/config-discord1.json
  freqtrade2:
    image: freqtrade_custom
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    # links:
    #   - "binance_proxy"
    # depends_on:
    #   - "binance_proxy"
    restart: unless-stopped
    container_name: freqtrade2
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./freqtrade_strategies:/freqtrade/freqtrade_strategies"
    # ports:
    #   - "127.0.0.1:8082:8081"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade2.log
      --config /freqtrade/user_data/config2.json
      --config /freqtrade/user_data/config-exchange2.json
      --config /freqtrade/user_data/config-exchange-general.json
    #  --config /freqtrade/user_data/config-exchange-general-binance-proxy-docker.json
    #  --config /freqtrade/user_data/config-exchange-general-binance-proxy-futures.json
    #  --config /freqtrade/user_data/config-exchange-general-docker-kucoin.json
      --config /freqtrade/user_data/config-exchange-blacklist.json
      --config /freqtrade/user_data/config-telegram2.json
      --config /freqtrade/user_data/config-telegram-general.json
    #  --config /freqtrade/user_data/config-discord2.json
  freqtrade3:
    image: freqtrade_custom
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    # links:
    #   - "binance_proxy"
    # depends_on:
    #   - "binance_proxy"
    restart: unless-stopped
    container_name: freqtrade3
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./freqtrade_strategies:/freqtrade/freqtrade_strategies"
    # ports:
    #   - "127.0.0.1:8083:8081"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade3.log
      --config /freqtrade/user_data/config3.json
      --config /freqtrade/user_data/config-exchange3.json
      --config /freqtrade/user_data/config-exchange-general.json
    #  --config /freqtrade/user_data/config-exchange-general-binance-proxy-docker.json
    #  --config /freqtrade/user_data/config-exchange-general-binance-proxy-futures.json
    #  --config /freqtrade/user_data/config-exchange-general-docker-kucoin.json
      --config /freqtrade/user_data/config-exchange-blacklist.json
      --config /freqtrade/user_data/config-telegram3.json
      --config /freqtrade/user_data/config-telegram-general.json
    #  --config /freqtrade/user_data/config-discord3.json
  freqtrade4:
    image: freqtrade_custom
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    # links:
    #   - "binance_proxy"
    # depends_on:
    #   - "binance_proxy"
    restart: unless-stopped
    container_name: freqtrade4
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./freqtrade_strategies:/freqtrade/freqtrade_strategies"
    # ports:
    #   - "127.0.0.1:8084:8081"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade4.log
      --config /freqtrade/user_data/config4.json
      --config /freqtrade/user_data/config-exchange4.json
      --config /freqtrade/user_data/config-exchange-general.json
    #  --config /freqtrade/user_data/config-exchange-general-binance-proxy-docker.json
    #  --config /freqtrade/user_data/config-exchange-general-binance-proxy-futures.json
    #  --config /freqtrade/user_data/config-exchange-general-docker-kucoin.json
      --config /freqtrade/user_data/config-exchange-blacklist.json
      --config /freqtrade/user_data/config-telegram4.json
      --config /freqtrade/user_data/config-telegram-general.json
    #  --config /freqtrade/user_data/config-discord4.json

  # binance_proxy:
  #   image: nightshift2k/binance-proxy:latest
  #   container_name: binance_proxy
  #   restart: unless-stopped
  #   ports:
  #     - "127.0.0.1:8090:8090"

  # kucoin-proxy:
  #   image: mikekonan/exchange-proxy:latest-amd64
  #   restart: unless-stopped
  #   command: -verbose 1
  #   container_name: kucoin-proxy
